import UIKit
import Foundation

struct ExamplesModel {
    
    let img: String
    let title: String
    let time: String
    let type: String
}

let yoga_1Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "",
                  time: "",
                  type: "")
]

//MARK:- Похудение

let slimming_1Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Выпрыгивание из приседа",
                  time: "1 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Отжимания",
                  time: "1 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Прыжки с касанием",
                  time: "1 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Обратная планка с касанием стопы",
                  time: "1 мин.",
                  type: "Workout")
]

let slimming_2Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Сустовная разминка",
                  time: "5 мин.",
                  type: "Разминка"),
    ExamplesModel(img: "",
                  title: "Услажненные выпады в движении",
                  time: "12-15 выпадов на кажду ногу",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Отжимания от скамьи с прыжком",
                  time: "10-15 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Зашагивание с махом ногой",
                  time: "20-25 повторений для каждой ноги",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Приседания на одной ноге",
                  time: "10-15 повторений для каждой ноги",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Складывание на пресс",
                  time: "20-30 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Скручивания",
                  time: "20-25 раз на каждую сторону",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Растяжка",
                  time: "5 мин.",
                  type: "Заминка"),
]

let slimming_3Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Одиночные простые прыжки",
                  time: "1 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Прыжки назад",
                  time: "1 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Прыжки на одной ноге",
                  time: "1 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Прыжки в стороны",
                  time: "1 мин.",
                  type: "Workout")
]

let slimming_4Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Бег",
                  time: "2,5 час  = 1000 ккал.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Велосипед",
                  time: "4 часа = 1000 ккал.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Скакалка",
                  time: "1,6 часов = 1000 ккал.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Бурпи",
                  time: "714 бурпи  = 1000 ккал.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Ходьба",
                  time: "5 часов  = 1000 ккал.",
                  type: "Workout")
]

let slimming_5Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Прыжки с выпадом",
                  time: "20 сек.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Прыжки в планке",
                  time: "20 сек.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Присед с прыжком",
                  time: "20 сек.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Боковое скручивание с касанием пяток",
                  time: "20 сек.",
                  type: "Workout")
]

let slimming_6Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Присед с махом",
                  time: "1 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Берпи с приседом",
                  time: "1 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Прыжки в планке",
                  time: "1 мин.",
                  type: "Workout")
]

//MARK:- Рельф

let relief_1Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Присед с махом",
                  time: "10 мин.",
                  type: "Разминка"),
    ExamplesModel(img: "",
                  title: "Первый круг",
                  time: "8 раз по 20 сек.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Второй круг",
                  time: "8 раз по 20 сек.",
                  type: "Workout"),
    ExamplesModel(img: "",
                   title: "Третий круг",
                   time: "8 раз по 20 сек.",
                   type: "Workout"),
    ExamplesModel(img: "",
                   title: "Четвертй круг",
                   time: "8 раз по 20 сек.",
                   type: "Workout"),
    ExamplesModel(img: "",
                  title: "Пятый круг",
                  time: "8 раз по 20 сек.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Шестой круг",
                  time: "8 раз по 20 сек.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Седьмой круг",
                  time: "8 раз по 20 сек.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Восьмой круг",
                  time: "8 раз по 20 сек.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Прыжки в планке",
                  time: "10 мин.",
                  type: "Заминка")
]

let relief_2Array: [ExamplesModel] = [ 
    ExamplesModel(img: "",
                  title: "Выпад с приседом и прыжком",
                  time: "2 раз по 20 сек.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Отжимания с приведением ноги к плечу",
                  time: "2 раз по 20 сек.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Плие с поднятием колена",
                  time: "2 раз по 20 сек.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Планка с переносом стопы и прыжком",
                  time: "2 раз по 20 сек.",
                  type: "Workout")
]

let relief_3Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Упражнение 1",
                  time: "15 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Упражнение 2",
                  time: "1 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Упражнение 3",
                  time: "15-20 повторений на каждую сторону",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Упражнение 4",
                  time: "1 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Упражнение 5",
                  time: "15-20 повторений",
                  type: "Workout")
]

let relief_4Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Альпинист",
                  time: "30 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Велосипед",
                  time: "30 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Шаги в планке",
                  time: "20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Ножницы",
                  time: "20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Планка на предплечьях",
                  time: "45 сек.",
                  type: "Workout")
]

let relief_5Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Скручивания с одновременным подъемом таза",
                  time: "20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Диагонольная скручивания",
                  time: "8 повторений на каждую сторону",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Отведение ног в сторону",
                  time: "15 повторений в каждую сторону",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Вытяжение за рукой к стопе",
                  time: "15 повторений в каждую сторону",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Боковые скручивания",
                  time: "16 повторений в каждую сторону",
                  type: "Workout")
]

let relief_6Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Скручивания к ноге",
                  time: "1 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Прыжок, прыжок, присед",
                  time: "1 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Альпинист",
                  time: "1 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Выпад + Планка",
                  time: "1 мин.",
                  type: "Workout")
]

//MARK:- Сила

let streight_1Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Приседания Реверанc",
                  time: "3 подхода по 12-20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Выпад с махом",
                  time: "12-20 повторений на каждую ногу",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Тяга к планке",
                  time: "30 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Стойка",
                  time: "25-30 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Скручивания",
                  time: "50 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Крокодил",
                  time: "20 повторений",
                  type: "Workout"),
]

let streight_2Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Классические приседания",
                  time: "20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Плие",
                  time: "20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Приседания с узкой постановкой стоп",
                  time: "20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Приседания Реверанс",
                  time: "20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Приседания с прыжком",
                  time: "20 повторений",
                  type: "Workout"),
]

let streight_3Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Вращения плечами",
                  time: "12 вперед и назад",
                  type: "Разминка"),
    ExamplesModel(img: "",
                  title: "Вращения разведенными руками ",
                  time: "12 вперед и назад",
                  type: "Разминка"),
    ExamplesModel(img: "",
                  title: "Поднимание в согнутых локтях рук",
                  time: "10 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Давление-сопротивление",
                  time: "10 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Классические отжимания",
                  time: "10 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Разведение рук с гантелями лежа",
                  time: "10-15 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Жим гателей лежа",
                  time: "10-15 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Отведение плеч назад",
                  time: "20-30 сек.",
                  type: "Заминка"),
]

let streight_4Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Глубокий присед с мячом",
                  time: "3 подхода по 25 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Присед в плие с весом",
                  time: "4 подхода по 20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Отведение ног в стороны",
                  time: "3 подхода по 25 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Мостик на фитболе",
                  time: "3 подхода по 30 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Выпады с гантелями ",
                  time: "3 подхода по 20 повторений на каждую ногу",
                  type: "Workout"),
]

let streight_5Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Выпады",
                  time: "3 подхода по 20 повторений на каждую ногу",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Подъем ног",
                  time: "3 подхода по 20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Подъем таза ",
                  time: "3 подхода по 20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Ножницы",
                  time: "3 подхода по 1 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Махи",
                  time: "3 подхода по 15 повторений на каждую ногу",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Скручивания ",
                  time: "3 подхода по 1 мин.",
                  type: "Workout")
]

let streight_6Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Жим гантелей",
                  time: "3 подхода по 15 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Отжимания от пола",
                  time: "3 подхода по 8 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Французский жим",
                  time: "3 подхода по 10 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Подъем гантелей перед собой",
                  time: "3 подхода по 10 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Разгибание рук от локтя",
                  time: "3 подхода по 10 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Упражнение на верхний и нижний пресс",
                  time: "3 подхода по 10 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Упражнение для боковых мышц пресса",
                  time: "3 подхода по 10 повторений",
                  type: "Workout")
]

let streight_7Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Косые выпады с замахом",
                  time: "15 повторений на каждую ногу",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Отжимания от степа",
                  time: "3 подхода по 12 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Приседания с выпадом со степа",
                  time: "10 повторений на каждую ногу",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Разгибания рук в локтях в наклоне",
                  time: "3 подхода по 12-15 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Подъем таза на пятке",
                  time: "20 повторений на каждую ногу",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Скручивания на прямую ногу",
                  time: "20 повторений на каждую ногу",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Опускание прямых ног",
                  time: "3 подхода по 15 повторений на каждую ногу",
                  type: "Workout")
]

let streight_8Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Отведение ноги",
                  time: "20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Подъем ноги",
                  time: "20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Подъем бедра",
                  time: "20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Сгибание-разгибание ноги",
                  time: "20 повторений",
                  type: "Workout")
]

let streight_9Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Планка на предплечьях",
                  time: "1 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Отведение ног в сторону",
                  time: "16 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Разведение ног прыжком",
                  time: "15-20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Поворот в боковую планку",
                  time: "10 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Подъем таза",
                  time: "10 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Подтягивание коленей к груди",
                  time: "16 повторений",
                  type: "Workout"),
]

let streight_10Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Приседания",
                  time: "3-4 подхода по 12-15 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Приседания в плие",
                  time: "3-4 подхода по 12-15 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Выпады",
                  time: "3-4 подхода по 12-15 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Альпинист",
                  time: "40-50 сек.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Подъем таза",
                  time: "3 подхода по 15 повторений на каждую ногу",
                  type: "Workout")
]

let streight_11Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Прыжки в выпадах",
                  time: "3 подхода по 20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Приседания с киком",
                  time: "3 подхода по 15 повторений на каждую ногу",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Боковые приседания",
                  time: "3 подхода по 15 повторений на каждую ногу",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Сумо с поднятием колена",
                  time: "3 подхода по 20 повторений на каждую ногу",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Выпад с пряжком",
                  time: "3 подхода по 20 повторений на каждую ногу",
                  type: "Workout")
]

let streight_12Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Махи в положении лежа",
                  time: "3 подхода по 20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Стойка",
                  time: "3 подхода по 15-20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Скручивания с мячом",
                  time: "8 повторений на каждую сторону",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Поднятие таза",
                  time: "3 подхода по 15-20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Мостик",
                  time: "3 подхода по 20 повторений на каждую ногу",
                  type: "Workout")
]

let streight_14Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Скручивания в планке",
                  time: "30 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Лодочка",
                  time: "30 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Боковая планка",
                  time: "25 повторений на каждую сторону",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Приседания с коленей",
                  time: "25 повторений на каждую сторону",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Боковые скручивания",
                  time: "25-30 повторений на каждую сторону",
                  type: "Workout")
]

let streight_15Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Вращение коленей",
                  time: "1-3 мин. на каждое колено",
                  type: "Разминка"),
    ExamplesModel(img: "",
                  title: "Ходьба с высоко поднятыми коленями",
                  time: "3 мин.",
                  type: "Разминка"),
    ExamplesModel(img: "",
                  title: "Вращение бедрами",
                  time: "1  мин.",
                  type: "Разминка"),
    ExamplesModel(img: "",
                  title: "Болгарские сплит-приседания",
                  time: "20 повторений на каждую ногу",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Приседания с махом",
                  time: "3 подхода по 20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Сумо",
                  time: "3 подхода по 20 повторений",
                  type: "Workout"),
]

let streight_16Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Отжимания от пола",
                  time: "10 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Планка с отведением руки",
                  time: "10 повторений для каждой руки",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Подъем гантелей на бицепс",
                  time: "15-20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Разгибания на трицепс за головой",
                  time: "15-20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Разведение гантелей в стороны",
                  time: "10-15 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Разгибания на трицепс",
                  time: "10-15 повторений",
                  type: "Workout"),
]

let streight_17Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Упражнение 1",
                  time: "10-15 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Упражнение 2",
                  time: "10-15 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Упражнение 3",
                  time: "15 повторений на каждую ногу",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Упражнение 4",
                  time: "15 повторений на каждую руку ",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Упражнение 5",
                  time: "10-15 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Упражнение 6",
                  time: "15 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Упражнение 7",
                  time: "15 повторений на каждую ногу ",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Упражнение 8",
                  time: "5-10 повторений на каждую ногу",
                  type: "Workout")
]

let streight_18Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Приседания",
                  time: "3 подхода по 20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Плие",
                  time: "3 подхода по 20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Ширачайшие мышцы спины",
                  time: "3 подхода по 20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Отжимания",
                  time: "3 подхода по 20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Бицепс",
                  time: "3 подхода по 20 повторений",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Трицепс",
                  time: "3 подхода по 20 повторений",
                  type: "Workout"),
]

let streight_19Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Отвод рук в наклоне",
                  time: "3 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Наклоны вперед",
                  time: "3 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Подъем корпуса со сведением локтей",
                  time: "3 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Тяга к поясу",
                  time: "3 мин.",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Ласточка",
                  time: "3 мин.",
                  type: "Workout")
]

let streight_20Array: [ExamplesModel] = [
    ExamplesModel(img: "",
                  title: "Скручивания с подъемом ноги",
                  time: "30 повторений на каждую сторону",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Прыжки с поворотом",
                  time: "30 повторений на каждую сторону",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Диагональные скручивания",
                  time: "30 повторений на каждую сторону",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Диагональный подъем колена",
                  time: "30 повторений на каждую сторону",
                  type: "Workout"),
    ExamplesModel(img: "",
                  title: "Боковые скручивания в талии",
                  time: "30 повторений на каждую сторону",
                  type: "Workout")
]
