import UIKit
import Foundation

struct WorkoutModel {
    
    let img: String
    let title: String
    let description: String
    let level: String
    let duration: Int
    let previewVideo: String
    let examples: [ExamplesModel]
    let titleSection: String
    let video: String
}

let yogaArray: [WorkoutModel] = [
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/1.png",
                  title: "Йога для похудения",
                  description: "Описане",
                  level: "Начинающий",
                  duration: 2,
                  previewVideo: "00.02.mp4",
                  examples: yoga_1Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/1.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/2.png",
                  title: "Йога для начинающих",
                  description: "Описание",
                  level: "Начинающий",
                  duration: 6,
                  previewVideo: "",
                  examples: yoga_1Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/2.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/3.png",
                  title: "Упражнение для стройных бедер",
                  description: "Описане",
                  level: "Средний",
                  duration: 3,
                  previewVideo: "",
                  examples: yoga_1Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/3.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/4.png",
                  title: "Пилатес для стройного тела",
                  description: "Описане",
                  level: "Средний",
                  duration: 3,
                  previewVideo: "",
                  examples: yoga_1Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/4.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/5.png",
                  title: "Упражнения для тонкой талии",
                  description: "Описане",
                  level: "Средний",
                  duration: 4,
                  previewVideo: "",
                  examples: yoga_1Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/5.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/6.png",
                  title: "Йога для начинающих",
                  description: "Описане",
                  level: "Начинающий",
                  duration: 2,
                  previewVideo: "",
                  examples: yoga_1Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/6.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/7.png",
                  title: "Упражнения для плоского живота",
                  description: "Описане",
                  level: "Продвинутый",
                  duration: 2,
                  previewVideo: "",
                  examples: yoga_1Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/7.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/8.png",
                  title: "Упражнения для здоровой спины",
                  description: "Описане",
                  level: "Средний",
                  duration: 4,
                  previewVideo: "",
                  examples: yoga_1Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/8.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/9.png",
                  title: "Пять асан для похудения",
                  description: "Описане",
                  level: "Продвинутый",
                  duration: 4,
                  previewVideo: "",
                  examples: yoga_1Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/9.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/10.png",
                  title: "Йога для начинающих",
                  description: "Описане",
                  level: "Начинающий",
                  duration: 2,
                  previewVideo: "",
                  examples: yoga_1Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/10.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/11.png",
                  title: "Упражнения для релаксации",
                  description: "Описане",
                  level: "Начинающий",
                  duration: 4,
                  previewVideo: "",
                  examples: yoga_1Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/11.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/12.png",
                  title: "Идеальная осанка",
                  description: "Описане",
                  level: "Средний",
                  duration: 4,
                  previewVideo: "",
                  examples: yoga_1Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/12.mp4")
]


let strenghtArray: [WorkoutModel] = [
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/img/1.png",
                 title: "Как накачать грудь",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "НАБОР",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/video/1.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/img/2.png",
                 title: "Тренировка ягодиц",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "НАБОР",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/video/2.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/img/3.png",
                 title: "Как накачать ягодицы дома",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "НАБОР",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/video/3.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/img/4.png",
                 title: "Как увеличить ягодицы",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "НАБОР",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/video/4.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/img/5.png",
                 title: "Лучшее для спины",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "НАБОР",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/video/5.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/img/6.png",
                 title: "Для красиыых рук",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "НАБОР",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/video/6.mp4"),
]

let reliefArray: [WorkoutModel] = [
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/img/1.png",
                 title: "Жиросжигающая тренировка",
                 description: "Описание",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РЕЛЬЕФ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/1.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/img/2.png",
                 title: "Система Tabata",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РЕЛЬЕФ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/2.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/img/3.png",
                 title: "Накачать пресс дома",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РЕЛЬЕФ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/3.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/img/41.png",
                 title: "Тренировка на пресс",
                 description: "Описание",
                 level: "Средний",
                 duration: 8,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РЕЛЬЕФ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/4.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/img/5.png",
                 title: "Упражнения для пресса",
                 description: "Описание",
                 level: "Средний",
                 duration: 5,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РЕЛЬЕФ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/5.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/img/6.png",
                 title: "Упругие ягодицы",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 5,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РЕЛЬЕФ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/6.mp4"),
]

let chargingArray: [WorkoutModel] = [
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/img/1.png",
                 title: "Утренняя тренировка",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "ЗАРЯДКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/video/1.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/img/2.png",
                 title: "Упражнения для похудения дома",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "ЗАРЯДКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/video/2.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/img/3.png",
                 title: "Упражнения для стройных бедер",
                 description: "Описание",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "ЗАРЯДКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/video/3.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/img/4.png",
                 title: "Упражнения дома",
                 description: "Описание",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "ЗАРЯДКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/video/4.mp4")
]

let cardioArray: [WorkoutModel] = [
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/1.png",
                 title: "Упражнения для пресса и ягодиц",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/1.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/2.png",
                 title: "Танцевальная тренировка",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/2.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/3.png",
                 title: "Домашняя кардио тренировка",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/3.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/4.png",
                 title: "Табата",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/4.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/5.png",
                 title: "Упражнения для стройных ног",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/5.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/6.png",
                 title: "Круговая тренировка",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/6.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/7.png",
                 title: "Система Табата",
                 description: "Описание",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/7.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/8.png",
                 title: "Функциональная тренировка",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 2,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/8.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/9.png",
                 title: "Разминка перед тренировкой",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/9.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/10.png",
                 title: "Интенсивное кардио",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/10.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/11.png",
                 title: "Упругие бедра и плоский живот",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/11.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/12.png",
                 title: "Тренировка HIT",
                 description: "Описание",
                 level: "Средний",
                 duration: 5,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/12.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/13.png",
                 title: "Стройное тело",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/13.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/14.png",
                 title: "Интервальная тренировка",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 5,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/14.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/15.png",
                 title: "Утреннее кардио",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/15.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/16.png",
                 title: "Высокоинтенсивная тренировка",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/16.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/17.png",
                 title: "Взрывное кардио",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/17.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/18.png",
                 title: "Упражнения для снижения веса",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/18.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/19.png",
                 title: "Упражнения для стройных ног",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/19.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/20.png",
                 title: "Тренировка для снижения веса",
                 description: "Описание",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/20.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/21.png",
                 title: "Фитнес в домашних условиях",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/21.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/22.png",
                 title: "Табата для похудения",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/22.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/23.png",
                 title: "Тренировка на рельеф",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/23.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/24.png",
                 title: "Как сжечь жир и сохранить мышцы",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/24.mp4")
]

let stretchingArray: [WorkoutModel] = [
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/1.png",
                 title: "Разминка перед тренировкой",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/1.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/2.png",
                 title: "Растяжка для начинающих",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/2.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/3.png",
                 title: "Эффективная растяжка ног",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 6,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/3.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/4.png",
                 title: "Растяжка ног",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/4.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/5.png",
                 title: "Упражнения для красивой осанки",
                 description: "Описание",
                 level: "Средний",
                 duration: 6,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/5.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/6.png",
                 title: "Сесть на поперечный шпагат",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/6.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/7.png",
                 title: "Как сделать тело гибким",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/7.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/8.png",
                 title: "Шпагат для начинающих",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/8.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/9.png",
                 title: "Йога для начинающих",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/9.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/10.png",
                 title: "Растяжка после тренировки",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/10.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/11.png",
                 title: "Колесо",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/11.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/12.png",
                 title: "Растяжка для начинающих",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/12.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/13.png",
                 title: "Шпагат за пять минут",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/13.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/14.png",
                 title: "Как встать на мостик",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/14.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/15.png",
                 title: "Танцевальная тренировка",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/15.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/16.png",
                 title: "Поперечный шпагат",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/16.mp4")
]

let slimmingArray: [WorkoutModel] = [
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/img/1.png",
                 title: "Как похудеть дома",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "ПОХУДЕНИЕ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/1.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/img/2.png",
                 title: "Стройное тело",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "ПОХУДЕНИЕ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/2.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/img/3.png",
                 title: "Кардио тренировка",
                 description: "Описание",
                 level: "Средний",
                 duration: 2,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "ПОХУДЕНИЕ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/3.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/img/4.png",
                 title: "Как сжечь 1000 калорий",
                 description: "Описание",
                 level: "Средний",
                 duration: 5,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "ПОХУДЕНИЕ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/4.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/img/5.png",
                 title: "Как похудеть за 4 минуты",
                 description: "Описание",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "ПОХУДЕНИЕ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/5.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/img/6.png",
                 title: "Взрывное кардио",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "ПОХУДЕНИЕ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/6.mp4"),
    
]

let musclegainArray: [WorkoutModel] = [
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/1.png",
                 title: "Тренировка для проблемных зон",
                 description: "Описание",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/1.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/2.png",
                 title: "100 приседаний для красивой попы",
                 description: "Описание",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/2.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/3.png",
                 title: "Упражнения для крупления грудных мышц",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/3.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/4.png",
                 title: "Тренировка ягодиц",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/4.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/5.png",
                 title: "BUMS + ABS",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/5.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/6.png",
                 title: "Тренировка для рук и спины",
                 description: "Описание",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/6.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/7.png",
                 title: "Силовая тренировка",
                 description: "Описание",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/7.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/8.png",
                 title: "Пять лучших упражнений для ягодиц",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/8.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/9.png",
                 title: "Силовые упражнения",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 2,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/9.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/10.png",
                 title: "Пять лучших упражнений для бедер",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/10.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/11.png",
                 title: "Упражнения для стройных ног",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/11.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/12.png",
                 title: "Упражнения с фитболом",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/12.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/14.png",
                 title: "Упражнения для боковых мыщц",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/14.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/15.png",
                 title: "Упражнения для стройных коленей",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/15.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/16.png",
                 title: "Упражнения для красивых рук",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/16.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/17.png",
                 title: "Упражнения с фитнес лентой",
                 description: "Описание",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/17.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/18.png",
                 title: "TRX Базовая тренировка",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/18.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/19.png",
                 title: "Упражнения для спины",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/19.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/20.png",
                 title: "Упражнения для пресса стоя",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/20.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/21.png",
                 title: "Как прокачать попу",
                 description: "Описание",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/21.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/22.png",
                 title: "Упражнения для спины",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/22.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/23.png",
                 title: "Тонкая талия за 7 минут",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/23.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/24.png",
                 title: "Пять лучших упражнений для ягодиц",
                 description: "Описание",
                 level: "Средний",
                 duration: 12,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/24.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/25.png",
                 title: "Как увеличить ягодицы",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/25.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/26.png",
                 title: "Как накачать руки",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/26.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/27.png",
                 title: "Бразильская попа",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/27.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/28.png",
                 title: "Как накачать ягодицы дома",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/28.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/29.png",
                 title: "Как накачать ягодицы",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/29.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/30.png",
                 title: "Утренний комплекс для пресса",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/30.mp4")
]
