import UIKit
import Foundation

struct WorkoutModel {
    
    let img: String
    let title: String
    let description: String
    let level: String
    let duration: Int
    let previewVideo: String
    let examples: [ExamplesModel]
    let titleSection: String
    let video: String
}

//MARK:- Йога

let yogaArray: [WorkoutModel] = [
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/1.png",
                  title: "Йога для похудения",
                  description: "Комплекс упражнений направлен на похудение",
                  level: "Начинающий",
                  duration: 2,
                  previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/1.mp4",
                  examples: yoga_1Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/1.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/2.png",
                  title: "Йога для начинающих",
                  description: "Комплекс упражнений для отличного настроения и хорошей фигуры",
                  level: "Начинающий",
                  duration: 6,
                  previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/2.mp4",
                  examples: yoga_2Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/2.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/3.png",
                  title: "Упражнение для стройных бедер",
                  description: "Пилатес для стройных бедер на свежем воздухе",
                  level: "Средний",
                  duration: 3,
                  previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/3.mp4",
                  examples: yoga_3Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/3.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/4.png",
                  title: "Пилатес для стройного тела",
                  description: "Копмлек упражнений для стройного и красивого тела",
                  level: "Средний",
                  duration: 3,
                  previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/4.mp4",
                  examples: yoga_4Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/4.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/5.png",
                  title: "Упражнения для тонкой талии",
                  description: "Пилатен для тонкой талии и гибкой фигуры",
                  level: "Средний",
                  duration: 4,
                  previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/5.mp4",
                  examples: yoga_5Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/5.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/6.png",
                  title: "Йога для начинающих",
                  description: "Асаны стоя для гибкого и пластичного тела",
                  level: "Начинающий",
                  duration: 2,
                  previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/6.mp4",
                  examples: yoga_6Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/6.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/7.png",
                  title: "Упражнения для плоского живота",
                  description: "Вакуум для плоского живота",
                  level: "Продвинутый",
                  duration: 2,
                  previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/7.mp4",
                  examples: yoga_7Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/7.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/8.png",
                  title: "Упражнения для здоровой спины",
                  description: "Пилатес для укрепления мышц спины и создания эластичности",
                  level: "Средний",
                  duration: 4,
                  previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/8.mp4",
                  examples: yoga_8Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/8.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/9.png",
                  title: "Пять асан для похудения",
                  description: "Йога для стройного тела на свежем воздухе",
                  level: "Продвинутый",
                  duration: 4,
                  previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/9.mp4",
                  examples: yoga_9Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/9.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/10.png",
                  title: "Йога для начинающих",
                  description: "Последовательный комплекс упражнений для приветствия солнцу",
                  level: "Начинающий",
                  duration: 2,
                  previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/10.mp4",
                  examples: yoga_10Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/10.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/11.png",
                  title: "Упражнения для релаксации",
                  description: "Копслек упражнения для релаксации и снятия стресса",
                  level: "Начинающий",
                  duration: 4,
                  previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/11.mp4",
                  examples: yoga_11Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/11.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/img/12.png",
                  title: "Идеальная осанка",
                  description: "Пилатес на свежем воздухе для создания идеальной осанки",
                  level: "Средний",
                  duration: 4,
                  previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/12.mp4",
                  examples: yoga_12Array,
                  titleSection: "ЙОГА & ПИЛАТЕС",
                  video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/yoga/video/12.mp4")
]

//MARK:- Набор

let strenghtArray: [WorkoutModel] = [
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/img/1.png",
                 title: "Как накачать грудь",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "НАБОР",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/video/1.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/img/2.png",
                 title: "Тренировка ягодиц",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "НАБОР",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/video/2.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/img/3.png",
                 title: "Как накачать ягодицы дома",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "НАБОР",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/video/3.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/img/4.png",
                 title: "Как увеличить ягодицы",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "НАБОР",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/video/4.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/img/5.png",
                 title: "Лучшее для спины",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "НАБОР",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/video/5.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/img/6.png",
                 title: "Для красиыых рук",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "НАБОР",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/strength/video/6.mp4"),
]

//MARK:- Рельеф

let reliefArray: [WorkoutModel] = [
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/img/1.png",
                 title: "Жиросжигающая тренировка",
                 description: "Круговая тренировка по система Tabata",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/1.mp4",
                 examples: relief_1Array,
                 titleSection: "РЕЛЬЕФ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/1.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/img/2.png",
                 title: "Система Tabata",
                 description: "Круговая жиросжигающая тренировка по системе Tabata. Максимальная интенсивность",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/2.mp4",
                 examples: relief_2Array,
                 titleSection: "РЕЛЬЕФ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/2.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/img/3.png",
                 title: "Накачать пресс дома",
                 description: "Спцеиальные комплекс упражнений на пресс",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/3.mp4",
                 examples: relief_3Array,
                 titleSection: "РЕЛЬЕФ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/3.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/img/41.png",
                 title: "Тренировка на пресс",
                 description: "Комплекс упражнений на пресс для хорошего настроения",
                 level: "Средний",
                 duration: 8,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/4.mp4",
                 examples: relief_4Array,
                 titleSection: "РЕЛЬЕФ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/4.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/img/5.png",
                 title: "Упражнения для пресса",
                 description: "Комплекс упражнений для пресса",
                 level: "Средний",
                 duration: 5,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/5.mp4",
                 examples: relief_5Array,
                 titleSection: "РЕЛЬЕФ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/5.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/img/6.png",
                 title: "Упругие ягодицы",
                 description: "Тренировка для ягодиц и пресса",
                 level: "Начинающий",
                 duration: 5,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/6.mp4",
                 examples: relief_6Array,
                 titleSection: "РЕЛЬЕФ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/relief/video/6.mp4"),
]

//MARK:- Зарядка

let chargingArray: [WorkoutModel] = [
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/img/1.png",
                 title: "Утренняя тренировка",
                 description: "Утренняя зарядка для поднятия настроения и бодрости на целый день",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/video/1.mp4",
                 examples: charging_1Array,
                 titleSection: "ЗАРЯДКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/video/1.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/img/2.png",
                 title: "Упражнения для похудения дома",
                 description: "Утренний комплекс упражнений для похудения",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/video/2.mp4",
                 examples: charging_2Array,
                 titleSection: "ЗАРЯДКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/video/2.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/img/3.png",
                 title: "Упражнения для стройных бедер",
                 description: "Утренный комплекс упражнений для стройных бедер и ягодиц",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/video/3.mp4",
                 examples: charging_3Array,
                 titleSection: "ЗАРЯДКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/video/3.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/img/4.png",
                 title: "Упражнения дома",
                 description: "Функциональная утренняя зарядка в домашних условиях",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/video/4.mp4",
                 examples: charging_4Array,
                 titleSection: "ЗАРЯДКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/charging/video/4.mp4")
]

//MARK:- Кардио

let cardioArray: [WorkoutModel] = [
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/1.png",
                 title: "Упражнения для пресса и ягодиц",
                 description: "Кардио тренировка с упражнениями для нижней части тела и пресса",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/1.mp4",
                 examples: cardio_1Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/1.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/2.png",
                 title: "Танцевальная тренировка",
                 description: "Танцевальная кардио тренировка",
                 level: "Продвинутый",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/2.mp4",
                 examples: cardio_2Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/2.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/3.png",
                 title: "Домашняя кардио тренировка",
                 description: "Как сжечь 500 калорий за одну тренировку",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/3.mp4",
                 examples: cardio_3Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/3.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/4.png",
                 title: "Tabata",
                 description: "Часовая круговая кардио тренировка по системе Tabata с отдыхом 10 сек.",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/4.mp4",
                 examples: cardio_4Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/4.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/5.png",
                 title: "Упражнения для стройных ног",
                 description: "Комплекс упражнений для стройных ног",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/5.mp4",
                 examples: cardio_5Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/5.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/6.png",
                 title: "Круговая тренировка",
                 description: "Круговая кардио тренировка",
                 level: "Продвинутый",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/6.mp4",
                 examples: cardio_6Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/6.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/7.png",
                 title: "Система Tabata",
                 description: "Круговая кардио тренировка по системе Tabata",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/7.mp4",
                 examples: cardio_7Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/7.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/8.png",
                 title: "Функциональная тренировка",
                 description: "Функционая тренировка направлена на развитие всех групп мышц",
                 level: "Продвинутый",
                 duration: 2,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/8.mp4",
                 examples: cardio_8Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/8.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/9.png",
                 title: "Разминка перед тренировкой",
                 description: "Разминочная тренировка перед основной тренировкой",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/9.mp4",
                 examples: cardio_9Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/9.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/10.png",
                 title: "Интенсивное кардио",
                 description: "Интенсивная кардио тренировка на свежем воздухе",
                 level: "Продвинутый",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/10.mp4",
                 examples: cardio_10Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/10.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/12.png",
                 title: "Тренировка HIT",
                 description: "Супер эффективная жиросжигающая интервальная кардио тренировка",
                 level: "Средний",
                 duration: 5,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/12.mp4",
                 examples: cardio_12Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/12.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/13.png",
                 title: "Стройное тело",
                 description: "Круговая интенсивная тренировка для создания стройного тела",
                 level: "Начинающий",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/13.mp4",
                 examples: cardio_13Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/13.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/14.png",
                 title: "Интервальная тренировка",
                 description: "Нескучная интервальная жиросжигающая тренировка",
                 level: "Начинающий",
                 duration: 5,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/14.mp4",
                 examples: cardio_14Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/14.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/15.png",
                 title: "Утреннее кардио",
                 description: "Круговая утреняя жиросжигающая кардио тренировка",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/15.mp4",
                 examples: cardio_15Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/15.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/16.png",
                 title: "HIT тренировка",
                 description: "Высокоинтенсивная и жиросжигающая кардио тренировка для создания стройного тела",
                 level: "Продвинутый",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/16.mp4",
                 examples: cardio_16Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/16.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/17.png",
                 title: "Взрывное кардио",
                 description: "Взрывная кардио тренировка в интенсивном темпе",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/17.mp4",
                 examples: cardio_17Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/17.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/18.png",
                 title: "Упражнения для снижения веса",
                 description: "Круговая жиросжигающая кардио тренировка",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/18.mp4",
                 examples: cardio_18Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/18.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/19.png",
                 title: "Упражнения для стройных ног",
                 description: "Комплекс упражнений для стройных и красивых ног",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/19.mp4",
                 examples: cardio_19Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/19.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/20.png",
                 title: "Тренировка для снижения веса",
                 description: "Круговая кардио тренировка на степ-платформе",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/20.mp4",
                 examples: cardio_20Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/20.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/21.png",
                 title: "Фитнес в домашних условиях",
                 description: "Простая круговая фитнес тренировка в домашних условиях",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/21.mp4",
                 examples: cardio_21Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/21.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/22.png",
                 title: "Табата для похудения",
                 description: "Высокоинтенсиваня тренировка по ситеме Tabata",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/22.mp4",
                 examples: cardio_22Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/22.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/23.png",
                 title: "Тренировка на рельеф",
                 description: "Круговая тренировка на свежем воздухе",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/23.mp4",
                 examples: cardio_23Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/23.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/img/24.png",
                 title: "Как сжечь жир и сохранить мышцы",
                 description: "Круговая функциональная жиросжигающая кардио тренировка",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/24.mp4",
                 examples: cardio_24Array,
                 titleSection: "КАРДИО",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/cardio/video/24.mp4")
]

//MARK:- Растяжка

let stretchingArray: [WorkoutModel] = [
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/1.png",
                 title: "Разминка перед тренировкой",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/1.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/2.png",
                 title: "Растяжка для начинающих",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/2.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/3.png",
                 title: "Эффективная растяжка ног",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 6,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/3.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/4.png",
                 title: "Растяжка ног",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/4.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/5.png",
                 title: "Упражнения для красивой осанки",
                 description: "Описание",
                 level: "Средний",
                 duration: 6,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/5.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/6.png",
                 title: "Сесть на поперечный шпагат",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/6.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/7.png",
                 title: "Как сделать тело гибким",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/7.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/8.png",
                 title: "Шпагат для начинающих",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/8.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/9.png",
                 title: "Йога для начинающих",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/9.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/10.png",
                 title: "Растяжка после тренировки",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/10.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/11.png",
                 title: "Колесо",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/11.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/12.png",
                 title: "Растяжка для начинающих",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/12.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/13.png",
                 title: "Шпагат за пять минут",
                 description: "Описание",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/13.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/14.png",
                 title: "Как встать на мостик",
                 description: "Описание",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/14.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/15.png",
                 title: "Танцевальная тренировка",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/15.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/img/16.png",
                 title: "Поперечный шпагат",
                 description: "Описание",
                 level: "Продвинутый",
                 duration: 4,
                 previewVideo: "",
                 examples: yoga_1Array,
                 titleSection: "РАСТЯЖКА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/stretching/video/16.mp4")
]

//MARK:- Похудение

let slimmingArray: [WorkoutModel] = [
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/img/1.png",
                 title: "Как похудеть дома",
                 description: "Кругоая тренировка в домашних условиях",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/1.mp4",
                 examples: slimming_1Array,
                 titleSection: "ПОХУДЕНИЕ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/1.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/img/2.png",
                 title: "Стройное тело",
                 description: "Круговая тренировка для создания стройного тела",
                 level: "Начинающий",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/2.mp4",
                 examples: slimming_2Array,
                 titleSection: "ПОХУДЕНИЕ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/2.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/img/3.png",
                 title: "Кардио тренировка",
                 description: "Прыжки на скакалке - это лучшее кардио в домашних условиях",
                 level: "Средний",
                 duration: 2,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/3.mp4",
                 examples: slimming_3Array,
                 titleSection: "ПОХУДЕНИЕ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/3.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/img/4.png",
                 title: "Как сжечь 1000 калорий",
                 description: "Сжигамем 1000 калорий каждый день разными способами",
                 level: "Средний",
                 duration: 5,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/4.mp4",
                 examples: slimming_4Array,
                 titleSection: "ПОХУДЕНИЕ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/4.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/img/5.png",
                 title: "Как похудеть за 4 минуты",
                 description: "Интервальная тренировка",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/5.mp4",
                 examples: slimming_5Array,
                 titleSection: "ПОХУДЕНИЕ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/5.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/img/6.png",
                 title: "Взрывное кардио",
                 description: "3 взрывных кардио упражнения в интенсивном темпе",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/6.mp4",
                 examples: slimming_6Array,
                 titleSection: "ПОХУДЕНИЕ",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/slimming/video/6.mp4"),
    
]

//MARK:- Сила

let musclegainArray: [WorkoutModel] = [
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/1.png",
                 title: "Тренировка для проблемных зон",
                 description: "Проробатывание мыщц проблемных зон и сжигание лишних калорий",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/1.mp4",
                 examples: streight_1Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/1.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/2.png",
                 title: "100 приседаний для красивой попы",
                 description: "Разнообразь свои приседания",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/2.mp4",
                 examples: streight_2Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/2.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/3.png",
                 title: "Упражнения для крупления грудных мышц",
                 description: "Простая тренировка для укрпления грудных мышц",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/3.mp4",
                 examples: streight_3Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/3.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/4.png",
                 title: "Тренировка ягодиц",
                 description: "Тренировка направлена на развитие ягодиц",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/4.mp4",
                 examples: streight_4Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/4.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/5.png",
                 title: "BUMS + ABS",
                 description: "Ягодицы и пресс. Тренировка для красивой фигуры",
                 level: "Продвинутый",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/5.mp4",
                 examples: streight_5Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/5.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/6.png",
                 title: "Тренировка для рук и спины",
                 description: "Тренировка для верхней части тела",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/6.mp4",
                 examples: streight_6Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/6.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/7.png",
                 title: "Силовая тренировка",
                 description: "Построй рельефное и подтянутое тело",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/7.mp4",
                 examples: streight_7Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/7.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/8.png",
                 title: "Пять лучших упражнений для ягодиц",
                 description: "Тренировка направлена укрепление бедер и ягодиц",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/8.mp4",
                 examples: streight_8Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/8.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/9.png",
                 title: "Силовые упражнения",
                 description: "Силавая тренировка в планке",
                 level: "Продвинутый",
                 duration: 2,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/9.mp4",
                 examples: streight_9Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/9.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/10.png",
                 title: "Пять лучших упражнений для бедер",
                 description: "Простой комплекс упражнений для красивых и упругих бедер",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/10.mp4",
                 examples: streight_10Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/10.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/11.png",
                 title: "Упражнения для стройных ног",
                 description: "Комплекс упражнений, которые сделают ваши ножки стройными",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/11.mp4",
                 examples: streight_11Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/11.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/12.png",
                 title: "Упражнения с фитболом",
                 description: "Упругие бедра и плоский живот",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/12.mp4",
                 examples: streight_12Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/12.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/14.png",
                 title: "Упражнения для боковых мыщц",
                 description: "Создай красивый и рельефный пресс за счет боковых мышц",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/14.mp4",
                 examples: streight_14Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/14.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/15.png",
                 title: "Упражнения для стройных коленей",
                 description: "Создаем стройные колени",
                 level: "Начинающий",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/15.mp4",
                 examples: streight_15Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/15.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/16.png",
                 title: "Упражнения для красивых рук",
                 description: "Комплекс для создания красивых и сильных рук",
                 level: "Продвинутый",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/16.mp4",
                 examples: streight_16Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/16.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/17.png",
                 title: "Упражнения с фитнес лентой",
                 description: "Пророботка мышц всего тела с помощью фитнес ленты",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/17.mp4",
                 examples: streight_17Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/17.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/18.png",
                 title: "TRX",
                 description: "Базовая круговая тренировка",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/18.mp4",
                 examples: streight_18Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/18.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/19.png",
                 title: "Упражнения для спины",
                 description: "Комплекс для укрепления мышц спины",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/19.mp4",
                 examples: streight_19Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/19.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/20.png",
                 title: "Упражнения для пресса стоя",
                 description: "Комплекс упражений для проработки пресса в положении стоя",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/20.mp4",
                 examples: streight_20Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/20.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/21.png",
                 title: "Как прокачать попу",
                 description: "Силовая тренировка для красивых ягодиц",
                 level: "Средний",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/21.mp4",
                 examples: streight_21Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/21.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/22.png",
                 title: "Упражнения для спины",
                 description: "Тренировка для мышц спины в тренажерном зале",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/22.mp4",
                 examples: streight_22Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/22.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/23.png",
                 title: "Тонкая талия за 7 минут",
                 description: "Круговая тренировка для тонкой и стройной талии",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/23.mp4",
                 examples: streight_23Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/23.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/24.png",
                 title: "Пять лучших упражнений для ягодиц",
                 description: "Круговая тренировка для сушки бедер с Екатериной Усмановой",
                 level: "Средний",
                 duration: 12,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/24.mp4",
                 examples: streight_24Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/24.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/25.png",
                 title: "Как увеличить ягодицы",
                 description: "Увеличиваем ягодицы в домашних условиях",
                 level: "Начинающий",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/25.mp4",
                 examples: streight_25Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/25.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/26.png",
                 title: "Как накачать руки",
                 description: "Пять упражнений для стройных и изящных рук в тренажерном зале",
                 level: "Продвинутый",
                 duration: 4,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/26.mp4",
                 examples: streight_26Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/26.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/27.png",
                 title: "Бразильская попа",
                 description: "Создаем бразильскую попу к лету в домашних условиях",
                 level: "Начинающий",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/27.mp4",
                 examples: streight_27Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/27.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/28.png",
                 title: "Как накачать ягодицы дома",
                 description: "Круговая тренировка для привлекательных ягодиц",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/28.mp4",
                 examples: streight_28Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/28.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/29.png",
                 title: "Как накачать ягодицы",
                 description: "Круговая тренировка направленная на улучшение формы ягодиц",
                 level: "Начинающий",
                 duration: 2,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/29.mp4",
                 examples: streight_29Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/29.mp4"),
    WorkoutModel(img: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/img/30.png",
                 title: "Утренний комплекс для пресса",
                 description: "Комплекс упражнений направленный на развитие пресса",
                 level: "Средний",
                 duration: 3,
                 previewVideo: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/30.mp4",
                 examples: streight_30Array,
                 titleSection: "СИЛА",
                 video: "https://s3.eu-north-1.amazonaws.com/workout.apps/workouts_section/musclegain/video/30.mp4")
]
